


#ifndef HEATER_COOLER_CONFIG_H_
#define HEATER_COOLER_CONFIG_H_

#define HEATINGELEMENTLED_PORT	    PORTD
#define HEATINGELEMENTLED_PIN		PIN0

#define HEATINGELEMENT_PORT         PORTD
#define HEATINGELEMENT_PIN          PIN1

#define COOLINGELEMENT_PORT         PORTD
#define COOLINGELEMENT_PIN          PIN4

#endif /* HEATER_COOLER_CONFIG_H_ */